### ISSUE TITLE
SZP014: Enable possibility for user to set logging level using config file

### ISSUE THREAD

**Issue by vendral** [vendral/szperacz#22]
Create `config.ini` file which will serve a purpose of configuration interface between user and application.
Create a field `LOG_LEVEL=` which can be set by user and read by app during startup (and apply to set logging level).

Consider using `configparser` lib: https://docs.python.org/3/library/configparser.html

**Comment by Jarogniev** [comment]
I have a question,
- 'config.ini' file should be like 'Logger.py', separate '.py' file? with everything related to log configuration?

**Comment by vendral** [comment]
Done
